version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: testing-express-api
    environment:
      MONGO_INITDB_ROOT_USERNAME: collins
      MONGO_INITDB_ROOT_PASSWORD: collins
      MONGO_INITDB_DATABASE: testing-express-api
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'
volumes:
  mongo:

